-- Highlight Normal and NonText with no background
-- vim.cmd('highlight Normal guibg=none')
-- vim.cmd('highlight NonText guibg=none')
-- vim.cmd('highlight Normal ctermbg=none')
-- vim.cmd('highlight NonText ctermbg=none')
-- vim.cmd('highlight Normal guibg=NONE ctermbg=NONE')
-- vim.cmd('highlight NonText guibg=NONE ctermbg=NONE')
-- vim.cmd('highlight SignColumn guibg=NONE ctermbg=NONE')
